#Plot3
> data <- read.csv("~/Documents/Exploratory Data Analysis/household_power_consumption.txt", sep=";", na.strings="?")
> data$Date <- as.Date(data$Date, format="%d/%m/%Y")
> data <- subset(data, subset=(Date >= "2007-02-01" & Date <= "2007-02-02"))
> png(filename="Plot3.png", width=480, height=480)
> plot.ts(data$Sub_metering_1, ylab="Energy sub metering")
> lines(data$Sub_metering_2, col="red")
> lines(data$Sub_metering_3, col="blue")
> legend("topright", lwd ="1" , col=c("black","red","blue"), legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
> dev.off()
